name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        uses: arnesor/gha-path-checker@master
        with:
          allow_non_ascii: false

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.errors }}" == "0"
